services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_POSTGRES_DB: cifarm
      POSTGRES_PASSWORD: Cuong123_A
    expose:
      - "5433"
    image: postgres:12.2-alpine
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: ciwallet-bots
    build:
      context: ..
    depends_on:
      - postgres
    env_file:
      - ../.env.docker
    environment:
      HENTAI: 1
    ports:
        - 9992:9992
volumes:
  data: 